import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/head";
import Footer from "../components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Header />
        <main className="p-10  not-only-of-type:p-6  text-white min-h-screen bg-gradient-to-b from-black to-orange-900">
          {children}
          <div className="p-6"></div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
